export const COLLECTION_IS_LOADING = "USERS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_USERS";
export const RECEIVED_RECORD = "RECEIVED_USER";
export const REMOVED_RECORD = "REMOVED_RECORD";
export const UPDATE_COLLECTION_QUERY = "UPDATE_USERS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_RECORD,
    REMOVED_RECORD,
    UPDATE_COLLECTION_QUERY
};
