export const COLLECTION_IS_LOADING = "JOURNALS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_JOURNALS";
export const RECEIVED_RECORD = "RECEIVED_JOURNAL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_JOURNALS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_RECORD,
    UPDATE_COLLECTION_QUERY
};
